=== CristianaMorais/SCRIPT_PDE/Trabalho 1/guiao.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ENTITY % TXT "(#PCDATA)">

<!ELEMENT guiao (cabecalho, cenas)>
<!ELEMENT cabecalho (personagens?, titulo, autor+, dataPublicacao, sinopse?)>

<!ELEMENT dataPublicacao (dia, mes, ano)>
<!ELEMENT titulo %TXT;>
<!ELEMENT autor %TXT;>
<!ELEMENT dia %TXT;>
<!ELEMENT mes %TXT;>
<!ELEMENT ano %TXT;>
<!ELEMENT sinopse %TXT;>

<!-- p -> personagem -->

<!ELEMENT personagens (personagem)+>
<!ATTLIST personagem
	p ID #REQUIRED>
    
<!ELEMENT personagem (nome, descricao)>
	
<!ELEMENT nome %TXT;>
<!ELEMENT descricao %TXT;>

<!ELEMENT cenas (personagens?, ( temporada* | episodio* | partes* | cena*))>

<!ELEMENT temporada (titulo, (personagens)?, (sinopse)?, episodio+)>
<!ATTLIST temporada
	id ID #REQUIRED>

<!ELEMENT episodio (titulo, (personagens)?, (sinopse)?, cena+)>
<!ATTLIST episodio
	id ID #REQUIRED>
	
<!ELEMENT partes (titulo, (personagens)?, (sinopse)?, cena+)>
<!ATTLIST partes
	id ID #REQUIRED>
	
<!ELEMENT cena (#PCDATA | fala | refere | comentario | adereco)*>
<!ATTLIST cena
	contexto CDATA #IMPLIED>
	
<!ELEMENT fala (#PCDATA | comentario)*>
<!ATTLIST fala
	p IDREF #REQUIRED>

<!ELEMENT comentario %TXT;>
<!ELEMENT refere %TXT;>
<!ATTLIST refere
	p IDREF #REQUIRED>

<!ELEMENT adereco %TXT;>

=== CristianaMorais/SCRIPT_PDE/Trabalho 2/guiao_dtd.xml
<?xml version="1.0"?>
<!--<!DOCTYPE guiao SYSTEM "guiao.dtd">-->

<guiao>
	<cabecalho>
		<personagens>
			<personagem p = "LS">
				<nome> Luck Skywalker </nome>
				<descricao> Ator, Guerra das estrelas </descricao>
			</personagem>
			<personagem p = "DV">
				<nome> Darth Vader </nome>
				<descricao> Ator, Guerra das estrelas </descricao>
			</personagem>
			<personagem p = "PG">
				<nome> Peter Griffin </nome>
				<descricao> Ator, Family Guy </descricao>
			</personagem>
		</personagens>

		<titulo>Trabalho da cadeira de Processamento de Documentos Estruturados</titulo>
		<autor> Cristiana Morais </autor>
		<autor> Rui Santos </autor>
		<dataPublicacao>
			<dia>28</dia>
			<mes>11</mes>
			<ano>2022</ano>
		</dataPublicacao>
	</cabecalho>

	<cenas>
		<temporada id="FriendsTEMP1">
			<titulo> Friends 1.0 </titulo>
			<personagens>
				<personagem p="RG1">
					<nome> Rachel Green </nome>
					<descricao> Jennifer Aniston </descricao>
				</personagem>
				<personagem p="MG1">
					<nome> Monica Geller </nome>
					<descricao> Courteney Cox </descricao>
				</personagem>
				<personagem p="PB1">
					<nome> Phoebe Buffay </nome>
					<descricao> Lisa Kudrow </descricao>
				</personagem>
				<personagem p="JT1">
					<nome> Joey Tribbiani </nome>
					<descricao> Matt LeBlanc </descricao>
				</personagem>
				<personagem p="CB1">
					<nome> Chandler Bing </nome>
					<descricao> Matthew Perry </descricao>
				</personagem>
				<personagem p="ROSSG1">
					<nome> Ross Geller </nome>
					<descricao> David Schwimmer </descricao>
				</personagem>
			</personagens>

			<sinopse>
				"A 1ª Temporada introduz os seis personagens principais: Rachel, Monica, Phoebe, Joey, 
				Chandler e Ross. Rachel chega no Central Perk, após deixar seu noivo Barry no altar e se 
				muda para o apartamento de Mônica. Ross tenta constantemente dizer a Rachel que a ama, 
				enquanto sua ex-esposa lésbica, Carol, está esperando seu bebê. Joey é apresentado como um 
				ator lutando por seu espaço, enquanto Phoebe trabalha como massagista. 
				Chandler termina com namorada Janice, que frequentemente retorna em outros episódios."
			</sinopse>
			<episodio id="EP1S1"> 
				<titulo> The One Where Monica Gets a Roommate </titulo>
				<sinopse>
					"Depois de deixar seu noivo, Barry, no altar, Rachel se encontra no Central Perk Café, 
					encharcada em seu vestido de noiva, procurando por sua velha amiga Monica. 
					Rachel acaba se mudando para o apartamento de Monica em Nova York. Chandler e Joey, 
					que moram do outro lado do corredor de Monica, consolam Ross depois que sua esposa Carol 
					acaba de deixá-lo por uma mulher. Monica, uma chef, se apaixona por "Paul the Wine Guy" 
					apenas para ser esmagada por sua noite de paixão ter sido apenas um caso de uma noite. 
					A turma pede que Rachel seja mais independente cortando os cartões de crédito de seu pai. 
					Rachel, que nunca trabalhou antes, recebe uma oferta de emprego de garçonete no 
					Central Perk. Ross, que tem uma queda por Rachel desde o colegial, a convida para sair."
				</sinopse>
				<cena contexto="Em casa">
					<refere p="MG1">Mónica entra na sua casa</refere> 
					Mónica senta-se no sofá quando ouve o telefone <adereco>Telefone fixo</adereco> a tocar. <comentario> O som do toque do telefone era muito alto </comentario>
                    É a sua amiga, Mónica diz :
					<fala p="MG1"> "O tempo tem estado terrível"</fala>	
				</cena>
			</episodio>
		</temporada>

		<temporada id="FSEASON2">
			<titulo> Friends 2.0 </titulo>
			<personagens>
				<personagem p="RG2">
					<nome> Rachel Green </nome>
					<descricao> Jennifer Aniston </descricao>
				</personagem>
				<personagem p="MG2">
					<nome> Monica Geller </nome>
					<descricao> Courteney Cox </descricao>
				</personagem>
				<personagem p="PB2">
					<nome> Phoebe Buffay </nome>
					<descricao> Lisa Kudrow </descricao>
				</personagem>
				<personagem p="JT2">
					<nome> Joey Tribbiani </nome>
					<descricao> Matt LeBlanc </descricao>
				</personagem>
				<personagem p="CB2">
					<nome> Chandler Bing </nome>
					<descricao> Matthew Perry </descricao>
				</personagem>
				<personagem p="ROSSG2">
					<nome> Ross Geller </nome>
					<descricao> David Schwimmer </descricao>
				</personagem>
			</personagens>

			<sinopse>
				"Uma nova temporada mais cheia de surpresas."
			</sinopse>
			<episodio id="EP1S2">
				<titulo> "The One with Ross's New Girlfriend" </titulo>
				<personagens>
					<personagem p="RossGirlf">
						<nome> Tina Rich </nome>
						<descricao> Maria Albertina </descricao>
					</personagem>
				</personagens>
				<sinopse>
					"Ross, Rachel, Mônica, Chandler, Joey e Phoebe formam um grupo de seis amigos que 
					lutam para se sobressair e progredir na competitiva vida de Manhattan. 
					Seu humor inteligente e apoio mútuo incondicional fazem com sua amizade seja cada vez 
					mais forte, superando assim todos os obstáculos que a vida lhes apresenta."
				</sinopse>
				<cena contexto="No café">
					<comentario> A nova namorada de Ross, uma jovem esbelta e alta </comentario>
					<refere p="ROSSG2">Referente a Ross</refere>
					<fala p="ROSSG2"> "Olá querida, olha o que trouxe para ti"</fala>
					<fala p="RossGirlf"> "Que querido, obrigada."</fala>
					<adereco>Rosa</adereco>
					<refere p="RossGirlf"> </refere>
					<comentario> A nova namorada de Ross ficou muito feliz.</comentario>
				</cena>
			</episodio>
		</temporada>
    </cenas>
</guiao>
